### ISSUE TITLE
Changes to README _only_ won't pass CI

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/acronyms#110]
From #109 
Ok, the CI requirements assume that you will be editing acronyms.csv. So as it stands, if you want to edit README.md you need to pair it with some change to the acronyms.csv or it will hang on acronym-lint. This seems like it could be adjusted, but I don't know how. @mchelen

**Comment by mchelen-gov** [comment]
Here is an attempt to fix this: https://github.com/department-of-veterans-affairs/acronyms/pull/112

**Comment by mchelen-gov** [comment]
Ok the fix is actually a little more complicated, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by mchelen-gov** [comment]
For simplicity sake, set all tests to run on PRs to `master`. This should prevent any "Required" checks from stalling. Confirmed working: https://github.com/department-of-veterans-affairs/acronyms/pull/116
