### ISSUE TITLE
Source code/repo for Slack bot

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/acronyms#14]
Hi,

Is the source code for the `/wtf` Slack command/bot also an open source repo?

cc @cmgiven

**Comment by cmgiven** [comment]
Yup! https://github.com/paultag/wtf

**Comment by karlbrown-va** [comment]
This is now here: https://github.com/department-of-veterans-affairs/wtf-bot

**Comment by ElijahLynn** [comment]
Thanks @karlbrown-va!
