### ISSUE TITLE
Write permissions to this repo?

### ISSUE THREAD

**Issue by franklin-hines** [department-of-veterans-affairs/acronyms#49]
The [README.md](https://github.com/department-of-veterans-affairs/acronyms/blob/master/README.md) indicates that "...Commits directly to `master` are welcome...", but I do not seem to have write permissions to the repo by default. If write permissions are expected to be extended to all in the [Dept of Veterans Affairs org](https://github.com/department-of-veterans-affairs) can the settings be reviewed and updated? Else, if write perms are not expected to be granted to all in the org, can the README.md be updated to note who has write permissions and how it can be obtained / whom to ask?

**Comment by mchelen-gov** [comment]
hmm weird, yeah there's a bunch of teams with write access but it's not va org wide

**Comment by karlbrown-va** [comment]
A few suggestions:
1) Change branch permissions to block commits to master, requiring PRs only, and requiring CI to pass before merging to master
2) Update CI to do additional checks against the acronyms file (such as requiring a non-empty definition)

**Comment by mchelen-gov** [comment]
> 1. Change branch permissions to block commits to master, requiring PRs only, and requiring CI to pass before merging to master

> Once the above is done we could add all-va with write permissions to this repo, making it easier for people to update acronyms.

:+1: to these, lmk if you need me to change config

**Comment by karlbrown-va** [comment]
I've added PR requirement to master branch and gave all-va write permissions, and it will require the acronym-lint to pass.
I also updated the documentation in 7bf52600a2

**Comment by karlbrown-va** [comment]
@franklin-hines @mchelen-gov do you think we need to do anything else?

**Comment by franklin-hines** [comment]
@karlbrown-va thanks, that's great. I think those improvements will suffice and this issue can be closed, but will leave open until Mike Chelen has a chance to weigh in.

**Comment by mchelen-gov** [comment]
For some reason the `@all-va` team got set to "read" access only, I've updated it to "write" again. Confirmed the branch protection rules require PRs. Please reopen if anyone has issues.
