### ISSUE TITLE
Add GH action to validate CSV on pull requests

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/acronyms#50]
run https://github.com/theodi/csvlint.rb in https://github.com/department-of-veterans-affairs/acronyms/blob/master/.github/workflows/acronym-lint.yml

resolves https://github.com/department-of-veterans-affairs/acronyms/issues/49

**Comment by karlbrown-va** [comment]
There are several scripts in the `scripts` directory, that check for mispellings, duplicate definitions, CSV linting, etc. We could define a process that runs some of these at least.

**Comment by karlbrown-va** [comment]
disabled the workflow as it isn't doing anything now. When somebody gets a chance they can re-enable this.

**Comment by karlbrown-va** [comment]
workflow now enabled against PRs to run csvlint on the acronyms file.
